pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: ${CI_REPO}
      tags: latest
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: [master, main]
